# Generated by Django 4.0.2 on 2022-05-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('role', models.CharField(choices=[('BACKEND_DEVELOPER', 'BACKEND_DEVELOPER'), ('FRONTEND_DEVELOPER', 'FRONTEND_DEVELOPER'), ('HR', 'HR'), ('DESINER', 'DESINER'), ('MOBILE_DEVELOPER', 'MOBILE_DEVELOPER')], max_length=20)),
            ],
        ),
    ]
