# Generated by Django 4.0.2 on 2022-05-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='registration_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
