# Generated by Django 4.0.2 on 2022-05-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_employees_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='role',
            field=models.CharField(choices=[('BACKEND_DEVELOPER', 'BACKEND_DEVELOPER'), ('FRONTEND_DEVELOPER', 'FRONTEND_DEVELOPER'), ('HR', 'HR'), ('DESINER', 'DESINER'), ('MOBILE_DEVELOPER', 'MOBILE_DEVELOPER')], max_length=20, null=True),
        ),
    ]
