# Generated by Django 4.0.2 on 2022-05-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_employees_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
